name: CI / Publish extension

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  tests:
    name: ğŸ§ª Tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: ğŸš€ Publish extension
    runs-on: ubuntu-latest
    environment: Production
    needs: [tests]
    env:
      PLASMO_PUBLIC_SITE_URL: ${{ secrets.SITE_URL }}
      PLASMO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PLASMO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      PLASMO_PUBLIC_AUTH_COOKIE_NAME: ${{ secrets.AUTH_COOKIE_NAME }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ“¦ Build
        run: pnpm build:extension

      - name: ğŸ—ƒï¸ Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: apps/extension/build/chrome-mv3-prod

      - name: ğŸ’¨ Publish!
        uses: PlasmoHQ/bpp@v3
        with:
          artifact: apps/extension/build/chrome-mv3-prod.zip
          keys: ${{ secrets.EXTENSION_SUBMIT_KEYS }}
