name: CI / Publish extension

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  tests:
    name: üß™ Tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: üöÄ Publish extension
    runs-on: ubuntu-latest
    environment: Production
    needs: [tests]
    env:
      PLASMO_PUBLIC_SITE_URL: ${{ secrets.SITE_URL }}
      PLASMO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PLASMO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      PLASMO_PUBLIC_AUTH_COOKIE_NAME: ${{ secrets.AUTH_COOKIE_NAME }}
      PLASMO_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
      PLASMO_PUBLIC_GOOGLE_ANALYTICS_SECRET: ${{ secrets.GOOGLE_ANALYTICS_SECRET }}

    steps:
      - name: ‚úÖ Checkout code
        uses: actions/checkout@v4

      - name: üî® Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: üì¶ Build
        run: pnpm build:extension

      - name: üóÉÔ∏è Archive Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-${{ github.sha }}
          path: apps/extension/build/chrome-mv3-prod

      - name: üóÉÔ∏è Archive Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-${{ github.sha }}
          path: apps/extension/build/firefox-mv2-prod

      - name: üí® Publish!
        uses: PlasmoHQ/bpp@v3
        with:
          chrome-file: apps/extension/build/chrome-mv3-prod.zip
          firefox-file: apps/extension/build/firefox-mv2-prod.zip
          keys: ${{ secrets.EXTENSION_SUBMIT_KEYS }}
