name: CI / Publish mobile

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  web:
    name: ğŸš€ Publish mobile
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¥ Run tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI / Tests

      - name: ğŸ’¾ Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: ğŸ§ª Test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled

      - name: ğŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ’¨ Publish!
        run: cd apps/mobile && eas build --platform all --profile preview --non-interactive --no-wait
        # run: cd apps/mobile && eas build --platform all --profile production --non-interactive --no-wait --auto-submit
