name: CI / Publish db

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  db:
    name: ğŸš€ Publish database
    runs-on: ubuntu-latest
    environment: Production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ” Check database
        run: pnpm db:check

      - name: ğŸ’¨ Migrate!
        run: pnpm db:migrate
