name: CI / Publish extension

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  web:
    name: ğŸš€ Publish extension
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¥ Run tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI / Tests

      - name: ğŸ’¾ Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: ğŸ§ª Test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled

      - name: ğŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ“¦ Build
        run: pnpm build:extension

      - name: ğŸ—ƒï¸ Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: apps/extension/build/chrome-mv3-prod

      - name: ğŸ’¨ Publish!
        uses: PlasmoHQ/bpp@v3
        with:
          artifact: apps/extension/build/chrome-mv3-prod.zip
          keys: ${{ secrets.EXTENSION_SUBMIT_KEYS }}
